blank_issues_enabled: false
contact_links:
  - name: HashDom Security Policy
    url: https://github.com/ZerkerEOD/hashdom/security/policy
    about: Please review our security policy for reporting security vulnerabilities. 