blank_issues_enabled: false
contact_links:
  - name: KrakenHashes Security Policy
    url: https://github.com/ZerkerEOD/krakenhashes/security/policy
    about: Please review our security policy for reporting security vulnerabilities. 