#!/usr/bin/env python3
"""
gen.py — Generate backend/internal/services/hashvalidator/data/patterns.go
from the vendored Name-That-Hash hashes.py.

Usage:
    python3 backend/scripts/gen_hash_patterns/gen.py

The script parses the upstream Python AST, extracts each Prototype's regex
pattern and the hashcat modes it covers, and emits a Go file containing a
JSON blob of {hashcat_mode -> {pattern, name, case_insensitive}}.

Regex patterns are not validated here — the Go side compiles them with
regexp.MustCompile and skips any that fail RE2 syntax (logged at startup).
This keeps the generator dependency-free (stdlib only).
"""

from __future__ import annotations

import ast
import json
import os
import re
import sys
import textwrap
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
UPSTREAM = REPO_ROOT / "backend/internal/services/hashvalidator/data/upstream/hashes.py"
OUTPUT = REPO_ROOT / "backend/internal/services/hashvalidator/data/patterns.go"
PINNED_COMMIT = "4717bf38e9ec6b86d3003d0fc0554d034ccccb8b"


@dataclass
class Entry:
    hashcat: int
    name: str
    pattern: str
    case_insensitive: bool


def extract_entries(source: str) -> list[Entry]:
    """Walk the AST of hashes.py and pull out (hashcat, name, regex, flag) tuples."""
    tree = ast.parse(source)
    entries: list[Entry] = []

    # Find the `prototypes = [...]` assignment
    proto_list = None
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "prototypes":
                    proto_list = node.value
                    break
            if proto_list is not None:
                break
    if proto_list is None or not isinstance(proto_list, ast.List):
        sys.exit("ERROR: could not locate `prototypes = [...]` in hashes.py")

    for proto_node in proto_list.elts:
        if not (isinstance(proto_node, ast.Call) and getattr(proto_node.func, "id", None) == "Prototype"):
            continue
        regex_pattern, ignore_case = _extract_regex(proto_node)
        if regex_pattern is None:
            continue
        for mode in _extract_modes(proto_node):
            entries.append(
                Entry(
                    hashcat=mode["hashcat"],
                    name=mode["name"],
                    pattern=regex_pattern,
                    case_insensitive=ignore_case,
                )
            )
    return entries


def _extract_regex(proto_call: ast.Call) -> tuple[str | None, bool]:
    """From a Prototype(regex=..., modes=...) call, return (pattern, case_insensitive)."""
    for kw in proto_call.keywords:
        if kw.arg != "regex":
            continue
        # Expect re.compile(r"...", re.IGNORECASE?) — an ast.Call.
        if not isinstance(kw.value, ast.Call):
            return None, False
        call = kw.value
        # The pattern is the first positional arg.
        if not call.args or not isinstance(call.args[0], ast.Constant) or not isinstance(call.args[0].value, str):
            return None, False
        pattern = call.args[0].value
        # Detect re.IGNORECASE in positional or keyword args.
        case_insensitive = False
        for a in call.args[1:]:
            if isinstance(a, ast.Attribute) and a.attr == "IGNORECASE":
                case_insensitive = True
            if isinstance(a, ast.Name) and a.id == "IGNORECASE":
                case_insensitive = True
        for k in call.keywords:
            if k.arg == "flags" and isinstance(k.value, ast.Attribute) and k.value.attr == "IGNORECASE":
                case_insensitive = True
        return pattern, case_insensitive
    return None, False


def _extract_modes(proto_call: ast.Call) -> list[dict]:
    """From Prototype(modes=[HashInfo(...), ...]), yield {hashcat, name} for entries with integer hashcat."""
    out: list[dict] = []
    for kw in proto_call.keywords:
        if kw.arg != "modes":
            continue
        if not isinstance(kw.value, ast.List):
            continue
        for hi in kw.value.elts:
            if not (isinstance(hi, ast.Call) and getattr(hi.func, "id", None) == "HashInfo"):
                continue
            hashcat = None
            name = None
            for k in hi.keywords:
                if k.arg == "hashcat" and isinstance(k.value, ast.Constant) and isinstance(k.value.value, int):
                    hashcat = k.value.value
                if k.arg == "name" and isinstance(k.value, ast.Constant) and isinstance(k.value.value, str):
                    name = k.value.value
            if hashcat is not None and name is not None:
                out.append({"hashcat": hashcat, "name": name})
    return out


GO_HEADER = """\
// Code generated by backend/scripts/gen_hash_patterns/gen.py — DO NOT EDIT.
//
// Source: github.com/HashPals/Name-That-Hash, name_that_hash/hashes.py
// Pinned commit: {commit}
//
// The upstream file is licensed under the GNU General Public License v3.0
// (see ./upstream/LICENSE and ./THIRD_PARTY_NOTICES.md). KrakenHashes is
// distributed under AGPL-3.0; the combined work remains AGPL-3.0 per
// GPL-3.0 §5. Attribution is preserved in this header and in
// THIRD_PARTY_NOTICES.md.

package data

// RawPattern holds one regex pattern as extracted from the upstream source.
// The Pattern string is the raw Python regex literal; the consumer is
// responsible for compiling it with Go's regexp package (RE2 syntax). Patterns
// that fail RE2 compilation are skipped at package init by the validator,
// with a log line so we can audit gaps.
type RawPattern struct {{
\tHashcatMode      int
\tName             string
\tPattern          string
\tCaseInsensitive  bool
}}

// RawPatterns is the full vendored list. Multiple entries may share a hashcat
// mode (e.g. when several name variants point at the same mode); the
// validator deduplicates by mode at init time.
var RawPatterns = []RawPattern{{
"""

GO_FOOTER = "}\n"


def main() -> int:
    if not UPSTREAM.exists():
        sys.exit(f"ERROR: upstream file missing: {UPSTREAM}")

    source = UPSTREAM.read_text(encoding="utf-8")
    entries = extract_entries(source)
    # Stable order: by hashcat mode then by name.
    entries.sort(key=lambda e: (e.hashcat, e.name))

    lines = [GO_HEADER.format(commit=PINNED_COMMIT)]
    for e in entries:
        lines.append(
            "\t{{HashcatMode: {mode}, Name: {name}, Pattern: {pattern}, CaseInsensitive: {ci}}},\n".format(
                mode=e.hashcat,
                name=_go_quote(e.name),
                pattern=_go_quote(e.pattern),
                ci="true" if e.case_insensitive else "false",
            )
        )
    lines.append(GO_FOOTER)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT} — {len(entries)} entries covering {len({e.hashcat for e in entries})} unique hashcat modes")
    return 0


def _go_quote(s: str) -> str:
    """Quote a string as a Go double-quoted literal. Uses %q semantics — Go strconv handles it
    the same way for printable Unicode. We avoid backticks because patterns may contain them."""
    # json.dumps gives us a valid double-quoted JSON string; Go's string literal
    # syntax is a strict subset of JSON's for the characters we care about
    # (printable ASCII + standard escapes), so this is safe here.
    return json.dumps(s, ensure_ascii=False)


if __name__ == "__main__":
    raise SystemExit(main())
