name: Deploy Documentation

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements-docs.txt'
      - '.github/workflows/deploy-docs.yml'
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements-docs.txt'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for git-revision-date-localized plugin

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements-docs.txt'

      - name: Install dependencies
        run: |
          pip install -r requirements-docs.txt

      - name: Deploy dev documentation with mike
        run: |
          # Deploy as 'dev' version
          mike deploy --push --update-aliases dev
          
          # Check if 'latest' exists, if not set dev as default temporarily
          if ! mike list | grep -q "latest"; then
            echo "No 'latest' version found, setting dev as default"
            mike set-default --push dev
          fi

  preview:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements-docs.txt'

      - name: Install dependencies
        run: |
          pip install -r requirements-docs.txt

      - name: Build preview with mike
        run: |
          mike deploy --no-push pr-${{ github.event.pull_request.number }}
          mike serve &
          sleep 5
          mkdir -p ./site
          wget -r -np -k -E -p -erobots=off -P ./site http://localhost:8000/pr-${{ github.event.pull_request.number }}/
          pkill -f "mike serve" || true

      - name: Upload preview artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-preview-pr-${{ github.event.pull_request.number }}
          path: ./site
          retention-days: 7

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '📚 Documentation preview has been built! Download the artifact from the Actions tab to review changes.'
            })