name: Initialize Mike Documentation

on:
  workflow_dispatch:
    inputs:
      initial_version:
        description: 'Initial version to deploy (e.g., 0.15.8)'
        required: true
        type: string
        default: '0.15.8'

permissions:
  contents: write

jobs:
  initialize-mike:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements-docs.txt'

      - name: Install dependencies
        run: |
          pip install -r requirements-docs.txt

      - name: Initialize mike and deploy initial version
        run: |
          VERSION="${{ github.event.inputs.initial_version }}"
          
          echo "Initializing mike documentation with version ${VERSION}"
          
          # Check if gh-pages branch exists
          if git ls-remote --heads origin gh-pages | grep -q gh-pages; then
            echo "gh-pages branch exists, fetching..."
            git fetch origin gh-pages:gh-pages
          else
            echo "Creating new gh-pages branch"
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initial gh-pages commit"
            git push origin gh-pages
            git checkout -
          fi
          
          # Deploy the initial version with latest alias
          echo "Deploying version ${VERSION} as latest"
          mike deploy --push --update-aliases "${VERSION}" latest
          
          # Set latest as the default version
          echo "Setting latest as default version"
          mike set-default --push latest
          
          # Deploy current main branch as dev
          echo "Deploying current branch as dev"
          mike deploy --push --update-aliases dev
          
          # List all versions
          echo "Deployed versions:"
          mike list

      - name: Create deployment summary
        run: |
          VERSION="${{ github.event.inputs.initial_version }}"
          echo "## Mike Documentation Initialization Complete 🎉" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Deployed Versions:" >> $GITHUB_STEP_SUMMARY
          echo "- **${VERSION}** (latest) - https://zerkereod.github.io/krakenhashes/" >> $GITHUB_STEP_SUMMARY
          echo "- **dev** - https://zerkereod.github.io/krakenhashes/dev/" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Next Steps:" >> $GITHUB_STEP_SUMMARY
          echo "1. Visit https://zerkereod.github.io/krakenhashes/ to see the versioned documentation" >> $GITHUB_STEP_SUMMARY
          echo "2. The version selector will appear in the header" >> $GITHUB_STEP_SUMMARY
          echo "3. Future pushes to main/master will update the 'dev' version" >> $GITHUB_STEP_SUMMARY
          echo "4. Future version tags will create new versioned documentation" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Available Versions:" >> $GITHUB_STEP_SUMMARY
          mike list >> $GITHUB_STEP_SUMMARY